app/agenda/urls.py
"""
    URLs da aplicação
"""

from django.urls import path
from app.agenda.views import *


app_name = 'app.agenda'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('compromisso/novo/', AdicionarCompromissoView.as_view(), name='novo_compromisso'),
    path('compromisso/<pk>/detalhes/', DetalhesCompromissoView.as_view(), name='detalhes_compromisso'),
    path('compromisso/<pk>/editar/', EditarCompromissoView.as_view(), name='editar_compromisso'),
    path('compromisso/<pk>/excluir/', ExcluirCompromissoView.as_view(), name='excluir_compromisso'),
    path('compromissos/exportar/', ExportarDadosView.as_view(), name='exportar_dados'),
]

hub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.agenda.urls')),
    path('', include('app.core.urls')),
]

app/agenda/models.py
"""
    Models da aplicação
"""

from django.db import models
from django.utils.translation import gettext as _
from django.contrib.auth.models import User


class Compromisso(models.Model):
    """Model de Compromisso"""
    STATUS = (
        ('A', _('Agendado')),
        ('C', _('Cancelado')),
        ('R', _('Realizado')),
    )

    # Atributos de Compromisso
    usuario = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='usuario', blank=False
    )
    nome_compromisso = models.CharField(
        _('Nome do compromisso'), max_length=120, blank=False
    )
    data = models.DateField(
        _('Data'), blank=False, auto_now_add=False
    )
    hora_inicio = models.TimeField(
        _('Hora de início'), blank=False, auto_now_add=False
    )
    hora_termino = models.TimeField(
        _('Hora de término'), blank=False, auto_now_add=False
    )
    local = models.CharField(
        _('Local'), max_length=120, blank=False
    )
    observacoes = models.TextField(
        _('Observações'), blank=True, null=True
    )
    status_compromisso = models.CharField(
        _('Status do compromisso'), max_length=1, choices=STATUS, default='A'
    )

    def __str__(self) -> str:
        return self.nome_compromisso

    class Meta:
        verbose_name = _('Compromisso')
        verbose_name_plural = _('Compromissos')
        db_table = 'compromissos'

app/agenda/forms.py
"""
    Forms utilizados na aplicação
"""

from django import forms
from app.agenda.models import Compromisso


class CompromissoForm(forms.ModelForm):
    """Form responsável pelo cadastro e atualização de um Compromisso"""
    class Meta:
        model = Compromisso
        fields = (
            'nome_compromisso',
            'data',
            'hora_inicio',
            'hora_termino',
            'local',
            'observacoes',
            'status_compromisso',
        )
        widgets = {
            'data': forms.DateInput(attrs={'type': 'date'}, format="%Y-%m-%d"),
            'hora_inicio': forms.TimeInput(attrs={'type': 'time'}, format="%H:%M"),
            'hora_termino': forms.TimeInput(attrs={'type': 'time'}, format="%H:%M"),
            'observacoes': forms.Textarea(attrs={'rows': 5}),
        }

app/agenda/views.py
"""
    Views da aplicação
"""

import os
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, View
from django.urls import reverse_lazy
from django.contrib import messages
from django.http import FileResponse
from django.core.exceptions import EmptyResultSet
from django.conf import settings
from app.agenda.models import Compromisso
from app.agenda.forms import CompromissoForm
from app.agenda.bussines import ValidaChoqueDeHorario
from app.agenda.functions import gera_csv, gera_excel


class AdicionarCompromissoView(LoginRequiredMixin, ValidaChoqueDeHorario, CreateView):
    """View responsável por adicionar um novo compromisso"""
    model = Compromisso
    template_name: str = 'agenda/adicionar.html'
    form_class = CompromissoForm
    success_url = reverse_lazy('app.agenda:home')


class DetalhesCompromissoView(LoginRequiredMixin, DetailView):
    """View responsável por exibir os detalhes de um compromisso"""
    model = Compromisso
    template_name: str = 'agenda/detalhes.html'


class EditarCompromissoView(LoginRequiredMixin, ValidaChoqueDeHorario, UpdateView):
    """View responsável por editar os dados de um compromisso"""
    model = Compromisso
    template_name: str = 'agenda/editar.html'
    form_class = CompromissoForm
    success_url = reverse_lazy('app.agenda:home')


class ExcluirCompromissoView(LoginRequiredMixin, DeleteView):
    """View responsável por realizar a exclusão de um compromisso"""
    model = Compromisso
    success_url = reverse_lazy('app.agenda:home')

    def delete(self, request, *args, **kwargs):
        messages.add_message(request, messages.SUCCESS, f'O compromisso <b>{self.get_object().nome_compromisso}</b> foi removido com sucesso!')
        return super().delete(request, *args, **kwargs)


class ExportarDadosView(LoginRequiredMixin, View):
    """View responsável por exportar os compromissos do usuário"""
    template_name = 'agenda/exportar.html'
    queryset = Compromisso.objects.all()

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        try:
            nome_arquivo = None
            queryset = self.queryset.filter(usuario=request.user)
            if request.POST.get('tipo_arquivo') == '1':
                nome_arquivo = gera_csv(queryset)
            else:
                nome_arquivo = gera_excel(queryset)
            arquivo = open(os.path.join(settings.BASE_DIR, f'media/temp/{nome_arquivo}'), 'rb')
            return FileResponse(arquivo, as_attachment=True)
        except EmptyResultSet:
            messages.add_message(request, messages.ERROR, 'Não há compromissos para serem exportados!')
            return render(request, self.template_name)


class HomeView(LoginRequiredMixin, ListView):
    """View principal, onde é exibido os compromissos do usuário em forma de calendário e lista"""
    model = Compromisso
    template_name: str = 'agenda/calendario.html'

    def get_queryset(self):
        queryset = Compromisso.objects.filter(usuario=self.request.user)
        if len(self.request.GET.dict()) != 0:
            queryset = queryset.filter(
                nome_compromisso__icontains=self.request.GET.get('nome_compromisso'),
                local__icontains=self.request.GET.get('local')
            )
            if self.request.GET.get('data_inicial') != '':
                queryset = queryset.filter(
                    data__gte=self.request.GET.get('data_inicial')
                )
            if self.request.GET.get('data_final') != '':
                queryset = queryset.filter(
                    data__lte=self.request.GET.get('data_final')
                )
            if self.request.GET.get('hora_inicial') != '':
                queryset = queryset.filter(
                    hora_inicio__gte=self.request.GET.get('hora_inicial')
                )
            if self.request.GET.get('hora_final') != '':
                queryset = queryset.filter(
                    hora_termino__lte=self.request.GET.get('hora_final')
                )
            if self.request.GET.get('status_compromisso') != '':
                queryset = queryset.filter(
                    status_compromisso=self.request.GET.get('status_compromisso')
                )
        return queryset

templates/agenda/adicionar.html
{% extends 'base.html' %} {% load widget_tweaks %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Novo Compromisso</h5>
    </div>
    <div class="card-body">
        <form method="post"> {% csrf_token %}
            <div class="row">
                <div class="mb-3">
                    <label for="{{ form.nome_compromisso.id_for_label }}" class="form-label">{{ form.nome_compromisso.label }}</label>
                    {{ form.nome_compromisso|add_class:'form-control' }}
                    {% if form.errors.nome_compromisso %}
                    <span id="nome_compromisso_error" class="error invalid-feedback">{{ form.nome_compromisso.errors }}</span>
                    {% endif %}
                </div>
                <div class="mb-3 col-md-4">
                    <label for="{{ form.data.id_for_label }}" class="form-label">{{ form.data.label }}</label>
                    {{ form.data|add_class:'form-control' }}
                    {% if form.errors.data %}
                    <span id="data_error" class="error invalid-feedback">{{ form.data.errors }}</span>
                    {% endif %}
                </div>
                <div class="mb-3 col-md-4">
                    <label for="{{ form.hora_inicio.id_for_label }}" class="form-label">{{ form.hora_inicio.label }}</label>
                    {{ form.hora_inicio|add_class:'form-control' }}
                    {% if form.errors.hora_inicio %}
                    <span id="hora_inicio_error" class="error invalid-feedback">{{ form.hora_inicio.errors }}</span>
                    {% endif %}
                </div>
                <div class="mb-3 col-md-4">
                    <label for="{{ form.hora_termino.id_for_label }}" class="form-label">{{ form.hora_termino.label }}</label>
                    {{ form.hora_termino|add_class:'form-control' }}
                    {% if form.errors.hora_termino %}
                    <span id="hora_termino_error" class="error invalid-feedback">{{ form.hora_termino.errors }}</span>
                    {% endif %}
                </div>
                <div class="mb-3 col-md-8">
                    <label for="{{ form.local.id_for_label }}" class="form-label">{{ form.local.label }}</label>
                    {{ form.local|add_class:'form-control' }}
                    {% if form.errors.local %}
                    <span id="local_error" class="error invalid-feedback">{{ form.local.errors }}</span>
                    {% endif %}
                </div>
                <div class="mb-3 col-md-4">
                    <label for="{{ form.status_compromisso.id_for_label }}" class="form-label">{{ form.status_compromisso.label }}</label>
                    {{ form.status_compromisso|add_class:'form-select' }}
                    {% if form.errors.status_compromisso %}
                    <span id="status_compromisso_error" class="error invalid-feedback">{{ form.status_compromisso.errors }}</span>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="{{ form.observacoes.id_for_label }}" class="form-label">{{ form.observacoes.label }}</label>
                    {{ form.observacoes|add_class:'form-control' }}
                    {% if form.errors.observacoes %}
                    <span id="observacoes_error" class="error invalid-feedback">{{ form.observacoes.errors }}</span>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-outline-success float-end"><i class="fas fa-save me-1"></i> Salvar</button>
                    <button id="btnCancelar" type="button" class="btn btn-outline-danger float-end me-2"><i class="fas fa-times me-1"></i> Cancelar</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    var btnCancelar = document.getElementById("btnCancelar");

    btnCancelar.addEventListener("click", voltaInicio);

    function voltaInicio() {
        window.open("{% url 'app.agenda:home' %}", "_self");
    }
</script>
{% endblock %}

templates/agenda/calendario.html
{% extends 'base.html' %} {% load static %}

{% block content %}
<div class="card">
    <div class="card-header">
        <form method="get">
            <div class="row">
                <div class="mb-1 col-md-4">
                    <label for="id_nome_compromisso" class="form-label">Nome do compromisso</label>
                    <input type="text" class="form-control form-control-sm" id="id_nome_compromisso" name="nome_compromisso">
                </div>
                <div class="mb-1 col-md-2">
                    <label for="id_data_inicial" class="form-label">Data inicial</label>
                    <input type="date" class="form-control form-control-sm" id="id_data_inicial" name="data_inicial">
                </div>
                <div class="mb-1 col-md-2">
                    <label for="id_data_final" class="form-label">Data final</label>
                    <input type="date" class="form-control form-control-sm" id="id_data_final" name="data_final">
                </div>
                <div class="mb-1 col-md-2">
                    <label for="id_hora_inicial" class="form-label">Hora inicial</label>
                    <input type="time" class="form-control form-control-sm" id="id_hora_inicial" name="hora_inicial">
                </div>
                <div class="mb-1 col-md-2">
                    <label for="id_hora_final" class="form-label">Hora final</label>
                    <input type="time" class="form-control form-control-sm" id="id_hora_final" name="hora_final">
                </div>
                <div class="mb-1 col-md-4">
                    <label for="id_local" class="form-label">Local</label>
                    <input type="text" class="form-control form-control-sm" id="id_local" name="local">
                </div>
                <div class="mb-1 col-md-4">
                    <label for="id_status_compromisso" class="form-label">Status do compromisso</label>
                    <select class="form-select form-select-sm" id="id_status_compromisso" name="status_compromisso">
                        <option value="">---</option>
                        <option value="A">Agendado</option>
                        <option value="C">Cancelado</option>
                        <option value="R">Realizado</option>
                    </select>
                </div>
                <div class="mb-1 col-md-2 d-flex flex-column">
                    <div class="mt-auto">
                        <button type="submit" class="btn btn-outline-primary btn-sm">Filtrar <i class="fa-solid fa-filter mr-1"></i></button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="card-body">
        <div id="calendario"></div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'plugins/fullcalendar/js/main.js' %}" type="text/javascript"></script>
<script src="{% static 'plugins/fullcalendar/js/pt-br.js' %}" type="text/javascript"></script>

<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', () => {
        var calendarioElement = document.getElementById('calendario');

        var calendario = new FullCalendar.Calendar(calendarioElement, {
            themeSystem: 'bootstrap5',
            headerToolbar: {
                left: 'prev,next today',
                center: 'title',
                right: 'dayGridMonth,listYear',
            },
            initialView: 'listYear',
            initialDate: new Date(),
            locale: 'pt-br',
            navLinks: true,
            editable: false,
            dayMaxEvents: true,
            selectable: true,
            events: [
                {% for object in object_list %}
                {
                    "title": "{{ object.nome_compromisso }}",
                    "start": "{{ object.data|date:'Y-m-d' }}" + "T" + "{{ object.hora_inicio|time:'H:i:s' }}",
                    "end": "{{ object.data|date:'Y-m-d' }}" + "T" + "{{ object.hora_termino|time:'H:i:s' }}",
                    "url": "{% url 'app.agenda:detalhes_compromisso' object.pk %}",
                    "backgroundColor": {% if object.status_compromisso == 'A' %}"#2980b9"{% elif object.status_compromisso == 'C' %}"#e74c3c"{% else %}"#27ae60"{% endif %},
                },
                {% endfor %}
            ],
            eventTimeFormat: {
                hour: '2-digit',
                minute: '2-digit',
                meridiem: false
            }
        });

        calendario.render();
    });
</script>
{% endblock %}

templates/agenda/detalhes.html
{% extends 'base.html' %} {% load widget_tweaks %}

{% block content %}
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <h5 class="card-title">Detalhes do Compromisso</h5>
            </div>
            <div class="col-md-6">
                <button type="button" class="btn btn-outline-danger btn-sm float-end" data-bs-toggle="modal" data-bs-target="#excluirModal"><i class="fa-solid fa-trash me-1"></i> Excluir</button>
                <a href="{% url 'app.agenda:editar_compromisso' object.pk %}" class="btn btn-outline-primary btn-sm float-end me-2"><i class="fa-solid fa-pen-to-square me-1"></i> Editar</a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="mb-3">
                <label class="form-label">Nome do compromisso</label>
                <input class="form-control" type="text" value="{{ object.nome_compromisso }}" readonly>
            </div>
            <div class="mb-3 col-md-4">
                <label class="form-label">Data</label>
                <input class="form-control" type="date" value="{{ object.data|date:'Y-m-d' }}" readonly>
            </div>
            <div class="mb-3 col-md-4">
                <label class="form-label">Hora de início</label>
                <input class="form-control" type="time" value="{{ object.hora_inicio|time:'H:i' }}" readonly>
            </div>
            <div class="mb-3 col-md-4">
                <label class="form-label">Hora de término</label>
                <input class="form-control" type="time" value="{{ object.hora_termino|time:'H:i' }}" readonly>
            </div>
            <div class="mb-3 col-md-8">
                <label class="form-label">Local</label>
                <input class="form-control" type="text" value="{{ object.local }}" readonly>
            </div>
            <div class="mb-3 col-md-4">
                <label class="form-label">Status do compromisso</label>
                <input class="form-control" type="text" value="{{ object.get_status_compromisso_display }}" readonly>
            </div>
            <div class="mb-3">
                <label class="form-label">Observações</label>
                <textarea class="form-control" rows="5" readonly>{{ object.observacoes }}</textarea>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="excluirModal" tabindex="-1" aria-labelledby="excluirModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="excluirModalLabel">Atenção!</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <p>Você tem certeza que deseja remover o compromisso: <b>{{ object.nome_compromisso }}</b>? A ação não pode ser revertida, caso decida continuar!</p>
        </div>
        <div class="modal-footer">
            <form action="{% url 'app.agenda:excluir_compromisso' object.pk %}" method="post"> {% csrf_token %}
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal"><i class="fa-solid fa-circle-xmark me-1"></i> Não</button>
                <button type="submit" class="btn btn-success"><i class="fa-solid fa-circle-check me-1"></i> Sim</button>
            </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

templates/agenda/editar.html
{% extends 'base.html' %} {% load widget_tweaks %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Editar Compromisso</h5>
    </div>
    <div class="card-body">
        <form method="post"> {% csrf_token %}
            <div class="row">
                <div class="mb-3">
                    <label for="{{ form.nome_compromisso.id_for_label }}" class="form-label">{{ form.nome_compromisso.label }}</label>
                    {{ form.nome_compromisso|add_class:'form-control' }}
                    {% if form.errors.nome_compromisso %}
                    <span id="nome_compromisso_error" class="error invalid-feedback">{{ form.nome_compromisso.errors }}</span>
                    {% endif %}
                </div>
                <div class="mb-3 col-md-4">
                    <label for="{{ form.data.id_for_label }}" class="form-label">{{ form.data.label }}</label>
                    {{ form.data|add_class:'form-control' }}
                    {% if form.errors.data %}
                    <span id="data_error" class="error invalid-feedback">{{ form.data.errors }}</span>
                    {% endif %}
                </div>
                <div class="mb-3 col-md-4">
                    <label for="{{ form.hora_inicio.id_for_label }}" class="form-label">{{ form.hora_inicio.label }}</label>
                    {{ form.hora_inicio|add_class:'form-control' }}
                    {% if form.errors.hora_inicio %}
                    <span id="hora_inicio_error" class="error invalid-feedback">{{ form.hora_inicio.errors }}</span>
                    {% endif %}
                </div>
                <div class="mb-3 col-md-4">
                    <label for="{{ form.hora_termino.id_for_label }}" class="form-label">{{ form.hora_termino.label }}</label>
                    {{ form.hora_termino|add_class:'form-control' }}
                    {% if form.errors.hora_termino %}
                    <span id="hora_termino_error" class="error invalid-feedback">{{ form.hora_termino.errors }}</span>
                    {% endif %}
                </div>
                <div class="mb-3 col-md-8">
                    <label for="{{ form.local.id_for_label }}" class="form-label">{{ form.local.label }}</label>
                    {{ form.local|add_class:'form-control' }}
                    {% if form.errors.local %}
                    <span id="local_error" class="error invalid-feedback">{{ form.local.errors }}</span>
                    {% endif %}
                </div>
                <div class="mb-3 col-md-4">
                    <label for="{{ form.status_compromisso.id_for_label }}" class="form-label">{{ form.status_compromisso.label }}</label>
                    {{ form.status_compromisso|add_class:'form-select' }}
                    {% if form.errors.status_compromisso %}
                    <span id="status_compromisso_error" class="error invalid-feedback">{{ form.status_compromisso.errors }}</span>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="{{ form.observacoes.id_for_label }}" class="form-label">{{ form.observacoes.label }}</label>
                    {{ form.observacoes|add_class:'form-control' }}
                    {% if form.errors.observacoes %}
                    <span id="observacoes_error" class="error invalid-feedback">{{ form.observacoes.errors }}</span>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-outline-success float-end"><i class="fas fa-save me-1"></i> Salvar alterações</button>
                    <button id="btnCancelar" type="button" class="btn btn-outline-danger float-end me-2"><i class="fas fa-times me-1"></i> Cancelar</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    var btnCancelar = document.getElementById("btnCancelar");

    btnCancelar.addEventListener("click", voltaInicio);

    function voltaInicio() {
        window.open("{% url 'app.agenda:home' %}", "_self");
    }
</script>
{% endblock %}

templates/agenda/exportar.html
{% extends 'base.html' %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Exportação de Dados</h5>
    </div>
    <div class="card-body">
        <div class="alert alert-primary" role="alert">
            Nessa tela é possível realizar a exportação dos seus compromissos para um arquivo CSV ou Excel.
        </div>
        <form method="post" id="form"> {% csrf_token %}
            <div class="mb-3">
                <label for="id_tipo_arquivo" class="form-label">Selecione o tipo de arquivo para iniciar a exportação</label>
                <select class="form-select" aria-label="Tipo de arquivo" id="id_tipo_arquivo" name="tipo_arquivo" required>
                    <option value="">---</option>
                    <option value="1">CSV</option>
                    <option value="2">Excel</option>
                </select>
            </div>
            <div class="mb-3">
                <button type="submit" class="btn btn-outline-success float-end">
                    <i class="fa-solid fa-file-export me-1"></i> Exportar dados
                </button>
                <button id="btnCancelar" type="button" class="btn btn-outline-danger float-end me-2"><i class="fas fa-times me-1"></i> Cancelar</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    var btnCancelar = document.getElementById('btnCancelar');

    btnCancelar.addEventListener("click", () => {
        window.open("{% url 'app.agenda:home' %}", "_self");
    });
</script>
{% endblock %}